### ISSUE TITLE
Blood Frenzy not applied as debuff on Arms preset

### ISSUE THREAD

**Issue by TheGroxEmpire** [marisa-ashkandi/tbcsim#4]
If you select arms warrior pre-raid preset, Blood Frenzy is not ticked by default as a debuff.

**Comment by secretbis** [comment]
This is actually intentional - the preset is talented into Blood Frenzy, so it will apply naturally from Deep Wounds.  BF does not have 100% uptime (unapplied until first crit, basically), so it is still a useful data point.  

You can see BF applying from Deep Wounds here, using the preset defaults:
![image](https://user-images.githubusercontent.com/56484534/110762627-d8e0f180-8205-11eb-83f1-ae65ff88f751.png)

However, the UI could definitely be more clear about the fact that the raid buffs/debuffs panels are meant to be buffs that the current character does not apply themselves.  

Thanks for the report!

**Comment by TheGroxEmpire** [comment]
Ah I see. I also noticed that Blood Frenzy was also not ticked on default for Fury Warrior and I just assumed that it's not being applied for Arms Warrior also.

**Comment by secretbis** [comment]
UI updated with more helpful text in the buffs/debuffs windows.
