### ISSUE TITLE
Hunter ability damage not properly calculated

### ISSUE THREAD

**Issue by CaptainJad** [marisa-ashkandi/tbcsim#46]
tbcsim/src/commonMain/kotlin/character/classes/hunter/abilities/SteadyShot.kt

This calculation uses weapon speed to calculate damage rather than the normalized 2.8 which has been confirmed on the tbc beta. These are some confirmed and relevant ability formulas:

Steady:
(EffectiveRAP * 0.2 + 150 + BaseWeaponDmgAvg * 2.8 / RangedWeaponSpeed + DamageBonuses) * GronnStalkerSSMod * RangeBaseDmgMod

Auto: 
(AmmoDamage + EffectiveRAP * RangedWeaponSpeed / 14 + Scope + BaseWeaponDmgAvg + DamageBonuses) * RangeBaseDmgMod

Multi-Shot:
(AmmoDamage + EffectiveRAP * 0.2 + Scope + BaseWeaponDmgAvg + DamageBonus + MultiShotSpellDmg) * RangeBaseDmgMod * BarrageMod * PvPGloveMod

Where RangeBaseDmgMod is multiple of The Beast Within, Ferocious Insp., Focused Fire, Slaying, Range Wep Spec, and Blood Frenzy

**Comment by secretbis** [comment]
Thanks!  That's an odd kind of normalization on Steady Shot 🤔 

Places where it says `BaseWeaponDmgAvg` must mean the normal weapon damage range, yes?  Otherwise SS would hit for the exact same amount every time.  

Auto-shot looks to be implemented correctly, and Multi-Shot is now AP-normalized, which should be a slight improvement for Marksman's Bow.

> Where RangeBaseDmgMod is multiple of The Beast Within, Ferocious Insp., Focused Fire, Slaying, Range Wep Spec, and Blood Frenzy

Talents and buffs/procs that apply to all abilities are not handled as part of ability-specific code.  If any of the above are active, they are applied as part of the final attack roll.
