### ISSUE TITLE
Trinket Sim Issues

### ISSUE THREAD

**Issue by Simplejakk** [marisa-ashkandi/tbcsim#76]
Someone closed this instead of fixing it. Only phase 1 trinkets register a proc or on-use effect.

**Comment by secretbis** [comment]
Hi!  It was closed because the trinkets from the original issue were implemented.  You may see something like "Closed in <commit_hash>", which means that a commit message described a fix to the issue.

![image](https://user-images.githubusercontent.com/56484534/123563103-a1239880-d767-11eb-8477-aeef227ee7a4.png)

See: https://github.com/marisa-ashkandi/tbcsim/commit/31748613f434c800d008991a83da149858b2fad9

**Comment by Simplejakk** [comment]
I mean, I just simmed 4 different trinkets.. none of the procs or on-use effects were present in the sim results.

**Comment by secretbis** [comment]
The build isn't even finished yet: https://github.com/marisa-ashkandi/tbcsim/runs/2927227558

Please be patient, the new code will be out soon!

**Comment by Simplejakk** [comment]
Thank you!
