### ISSUE TITLE
Enhance Shaman Missing Badge Leather helm

### ISSUE THREAD

**Issue by BraggerSmold** [marisa-ashkandi/tbcsim#83]
When trying to input gear I noticed that Mask of the Deceiver was missing in the enhance helm slot. Also adding in a second for enhance to choose their personal weapon enchants (WF MH, Flametongue OH)

**Comment by secretbis** [comment]
Looks like that badge gear got categorized as the wrong phase - I'll reupdate phase data from wowhead.  In the meantime, you can find it in by switching the gear filter at the top to Phase 3.  

Also, Enhance weapon enhancements are actually part of the precombat rotation, which you can edit on the right side of the page.  Since they are class-specific spells, it was just a bit simpler to implement it that way :)

Replacing the rotation items that say `Windfury Weapon (MH)` or `Windfury Weapon (OH)` with `Flametongue Weapon (MH)` or `Flametongue Weapon (OH)` will let you test them in any configuration.
