### ISSUE TITLE
inconsistent STR to AP for EP

### ISSUE THREAD

**Issue by salcideon** [marisa-ashkandi/tbcsim#86]
Looking at the EP page. As far as I can tell the STR is in direct linear relation to AP with 1 point of STR giving 2 points of AP. Considering a BoK buff, 1 point of str would be worth 1.1 * 1 str so 2.2AP.  I do not know of any other buff that affects only STR and not AP so these values seems inconsistent:

Arms
Attack Power:
1.00
Strength:
2.26

Fury
Attack Power:
1.00
Strength:
2.23

when for both specs STR should be simply 2.2

**Comment by secretbis** [comment]
This is expected - there will always be a slight margin of error, since the EP values are derived solely from simulation results.  The specific goal of these EP values is to eliminate human bias, and find true values from game mechanics only.  The tradeoff is a couple percentage points worth of error.  

However, EPs are always estimates - similar items should always be simmed on the desktop edition for as many iterations as your machine can reasonably handle.  EPs will help you generate a short list of items to deeply compare, but they cannot provide a definitive ranking alone.  

I actually use stats like Strength as baseline known-values to assess the margin of error on all EP results when they are generated - it's a good canary for general bugs in the EP system.

Arms is a higher-variance spec in general as compared to Fury, so its EP weights may be slightly more divergent.
