### ISSUE TITLE
Spell Misses vs Resists Issue

### ISSUE THREAD

**Issue by CyberQuackGames** [marisa-ashkandi/tbcsim#91]
I've been doing a bit of investigation into this with Shadow Priest work and wanted to get confirmation of a defect I believe is happening here. Under [Spell.kt](https://github.com/marisa-ashkandi/tbcsim/blob/main/src/commonMain/kotlin/mechanics/Spell.kt#L166-L174) for [attackRoll](https://github.com/marisa-ashkandi/tbcsim/blob/6910e1d9d487b2fdd881f99963a8ffc7301820be/src/commonMain/kotlin/mechanics/Spell.kt#L130) I noticed there are two `EventResult`s out of this one being for `RESIST` and `HIT`, however I believe we are missing either `MISS` or another `RESIST` in the 3rd roll for resist calculations:

```kotlin
        val resistAvgReduction = spellResistReduction(sp, school)
        if(isBinary) {
            // Make a third roll for full resist or not
            val fullResistRoll = Random.nextDouble()
            val fullResistMod = if(fullResistRoll < resistAvgReduction) { 0.0 } else { 1.0 }
            finalResult = Pair(finalResult.first * fullResistMod, finalResult.second)
        } else {
            finalResult = Pair(finalResult.first * (1 - resistAvgReduction), finalResult.second)
        }
```

Notice under binary calculations, the `fullResistMod` could be 0 or 1, however the finalResult will remain with the existing `EventResult`. What I noticed was some dots (e.g. SiphonLife, Corruption, and some of the new ones I'm working on) would have `EventResult.HIT`, but do 0 damage in the event logs over the course of the dot (Priest ones I'm working on), which isn't actually possible in the game as this would probably fall under a full resist and the rotation would try to recast the dot, but since the dot is actually applied as 0 the entire dot duration is negated in these binary resists.

I noticed in the existing SiphonLife / Corruption that they could essentially never miss due to never receiving `EventResult.MISS` (Also side note, I believe there is a second defect here where the dots are not correctly snap shotting as the dot damage is calculated on every tick):
```
if(result.second != EventResult.MISS) {
  sp.sim.target.addDebuff(CorruptionDot(sp))
}
```

I wasn't sure if the first `EventResult.RESIST` in `attackRoll` was intended to be a `EventResult.MISS` and this last one should be `EventResult.RESIST` or have both of them as a `EventResult.RESIST` though since the game doesn't actually differentiate

**Comment by secretbis** [comment]
> I wasn't sure if the first EventResult.RESIST in attackRoll was intended to be a EventResult.MISS and this last one should be EventResult.RESIST or have both of them as a EventResult.RESIST though since the game doesn't actually differentiate

You're definitely right about DoT spells checking for `MISS` instead of `RESIST` to apply their DoT!  They should be checking the latter, and that would inflate their connection rate a bit.  Great find!

> I've been doing a bit of investigation into this with Shadow Priest work and wanted to get confirmation of a defect I believe is happening here. Under Spell.kt for attackRoll I noticed there are two EventResults out of this one being for RESIST and HIT, however I believe we are missing either MISS or another RESIST in the 3rd roll for resist calculations:

From what I understand about spellcaster mechanics, chance to miss from spell hit rating is distinct from chance to resist due to school resistance. School resistance cannot be mitigated by spell hit rating, so it would not increase the initial spell miss chance.  This implies a distinct roll for resistance, which is what is implemented here.  
 
I think it's a little confusing since the game doesn't really differentiate well between a spell miss and a fully resisted crit/hit, since both just seem to show up as "resist".  Both are possible under the base mechanics, though.  

However, the distinction between a fully-resisted hit or crit and a spell miss is important, since one is caused by the target's school resistance, and the other is caused by lack of spell hit rating.  

On the other hand, the Spell mechanics are not returning the proper partial resist events.  This doesn't have any impact on damage, but would be needed if deeper analysis into partial resists is desired.

**Comment by secretbis** [comment]
Snapshotting is not implemented - back when I was writing that, I didn't know whether spells were still snapshotted or not for TBC, so elected to just skip it.  

It should be fairly trivial to implement - just add a new constructor argument to each DoT implementation class, send the character's current spell power on application, then reference that value instead of the character's current spell power on each tick.

Let me know if you'd like me to fixup the warlock spells!  Excited to see the priest work!

**Comment by CyberQuackGames** [comment]
Ok I think with my situation I was expecting a resist event for determining which proc to fire, but I was passing `result.first` directly to my spells due to snap shot damage. I can easily add zero checks though and just consider it resisted with a miss or true binary resist no problem.
